### ISSUE TITLE
[기능요구(Feature)]: 주석 작성을 위한 정의된 템플릿이 있는지 문의드립니다.

### ISSUE THREAD

**Issue by smile-jeong** [eGovFramework/egovframe-common-components#207]
### 연락처 Contact

devsmilejwb@gmail.com

### 추가 요청 기능명 Feature Name

주석 관리를 위한 표준 주석 템플릿

### 기능 상세 설명 Feature Description

안녕하세요.

이번에 처음 컨트리뷰션으로 참여하게 됐습니다.

현재 1차적으로는 주석을 전체적으로 통일 또는 보완하는 것을 생각중입니다.
2차적으로 이백행 리더님이 알려주신 부분들을 조금씩 적용 하려고 합니다.

아직 표준프레임워크에대한 적응(?) 또는 익숙함이 없어서 가급적이면 로직이나 소스에 문제 없는 범위로 우선
저의 역할 잡아 보았습니다.

쉽게 생각하고(?) 주석을 정리하려고 보니.. 생각보다 주석에 대한 문서표준이나 내용이 소스별로 파일별로 조금씩 상이하고
제각각인거 같습니다.

1차적으로...
이클립스 메뉴 : Window -> Preferences -> Java -> Code Style -> Code Templates -> Comments -> Types
와 같은 이클립스 설정을 통해서 누구나 동일한 주석으로의 패턴을 정의해서 진행하게 하면 조금은 효율적이고
빠른 가독성이 가능하지 않을까 생각을합니다.

2차적으로는 현재 표준프레임워크에서 사용하는 주석에 대한 정확한 표준화가 없는 부분에 대하여 표준화를 요청드립니다.

### 솔루션 상세 Solution Details

아래는 예시입니다.

/**
 * EgovComIndexController 클래스
 * 
 * <p>
 * 컴포넌트 설치 후 설치된 컴포넌트들을 IncludedInfo annotation을 통해 찾아낸 후
 * 화면에 표시할 정보를 처리하는 Controller 클래스<br>
 * notice :  
 *  개발시 메뉴 구조가 잡히기 전에 배포파일들에 포함된 공통 컴포넌트들의 목록성 화면에
 *  URL을 제공하여 개발자가 편하게 활용하도록 하기 위해 작성된 것으로,
 *  실제 운영되는 시스템에서는 적용해서는 안 됨
 *  실 운영 시에는 삭제해서 배포해도 좋음<br>
 * disclaimer :
 *  운영시에 본 컨트롤을 사용하여 메뉴를 구성하는 경우 성능 문제를 일으키거나
 *  사용자별 메뉴 구성에 오류를 발생할 수 있음

 * </p>
 *  * 
 * @author 공통컴포넌트 정**
 * @since 2011.08.26
 * @version 2.0.0
 * @see
 *
 * <pre>
 * << 개정이력(Modification Information) >>
 *
 *  수정일       수정자       수정내용
 *  ----------   --------   ---------------------------
 *  2011.08.26   정##            최초 생성
 *  2011.09.16   서##            컨텐츠 페이지 생성
 *  2011.09.26   이##            header, footer 페이지 생성
 *  2019.12.04   신##            KISA 보안코드 점검 : Map<Integer, IncludedCompInfoVO> map를 지역변수로 수정
 *  2020.07.08   신##            비밀번호를 수정한후 경과한 날짜 조회
 *  2020.08.28   정##            표준프레임워크 v3.10 개선
 * </pre>
 * 
 */

@Controller
public class EgovComIndexController {

위와 같은 내용으로 제 개인적인 표준을 잡고 몇가지 파일에 대하여 통일된 내용으로 진행중입니다.

위에 내용에 대하여 추가/변경에 대하여 정의해 주시면 해당내용으로 진행하고자 합니다. 감사합니다.

이클립스에서 표현되는 내용 전달드립니다.(참고 부탁드립니다)

![image](https://github.com/eGovFramework/egovframe-common-components/assets/80878595/9d2b0975-4ac5-467e-89c6-844844366732)

![image](https://github.com/eGovFramework/egovframe-common-components/assets/80878595/cd13349f-21f2-4505-9270-575b40cc4138)

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크 발전을 위한 소중한 의견 감사 드립니다.
