### ISSUE TITLE
pom.xml 수정 요청

### ISSUE THREAD

**Issue by Pinepond** [eGovFramework/egovframe-common-components#21]
1. test 에 사용할 junit dependency 가 빠져있습니다.
2. oracle, altibase, tibero dependency 설정항목
   필요하다면 /src/main/webapp/WEB-INF/lib 에 해당 lib 를 포함하거나,
   불필요한 부분이면, pom.xml 에서 해당 dependency 를 빼면 좋을 것 같습니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
