### ISSUE TITLE
[Bug]: 개인정보보호정책확인 등록화면에서 저장 버튼

### ISSUE THREAD

**Issue by danheean** [eGovFramework/egovframe-common-components#215]
### 연락처 Contact

danhee.an@gmail.com

### 오류 내용 Error Description

오류를 발견했어요. I found an error.

개인정보보호정책확인 등록페이지에서 등록이 안됨

![image](https://github.com/eGovFramework/egovframe-common-components/assets/21186414/eb13b5b8-0cfa-4d53-badb-22bd5688dc45)
![image](https://github.com/eGovFramework/egovframe-common-components/assets/21186414/9059e5d3-06c6-484c-9196-68324963586d)

validation이 textarea로 지정되어 있는데, ckeditor로 에디터가 변경이 되면서 textarea의 내용은 계속 비어 있어
오류가 발생하는 것으로 생각됩니다.

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. `510. 개인정보보호정책확인` 메뉴를 클릭한다.
 2. 개인정보보호정책 목록에서 등록 버튼을 클릭한다. 
 3. 제목과 내용을 입력한다.
 4. 오류를 확인한다. 
 5. 확인 과정에 아래 2건의 자바스크립트 오류가 발견되었습니다. 

### 환경정보 Environmental Information

 - OS정보 Operating System: Windows11
 - 표준프레임워크 버전 eGovFrame Version: 4.1
 - JDK(JRE) 정보: jdk8
 - WAS 정보: Tomcat 8.5.84
 - DB 정보: Mysql
 - 기타 환경 정보 Other environmental information:

### 어느 브라우저를 사용했나요? Which browser did you use?

Chrome

### 에러 로그 Error Logs

EgovIndvdlInfoPolicyList.jsp
아래 onclick 부분도 확인 필요합니다. 
- `onclick="fn_userChk('USRCNFRM_00000000000')"`
```
	<div class="search_box" title="<spring:message code="common.searchCondition.msg" />"><!-- 이 레이아웃은 하단 정보를 대한 검색 정보로 구성되어 있습니다 -->
		<ul>
			<li>
				<select title="<spring:message code="select.searchCondition"/>" name="searchCondition" class="select"><!-- 개인정보보호정책조회 조건 -->
					<option value=''>--<spring:message code="input.select"/>--</option><!-- 선택하세요 -->
					<option value='INDVDL_INFO_POLICY_NM' <c:if test="${searchCondition == 'INDVDL_INFO_POLICY_NM'}">selected</c:if>><spring:message code="ussSamIpm.indvdlInfoPolicyList.indvdlInfoPolicyNm"/></option><!-- 개인정보보호정책명 -->
					<option value='INDVDL_INFO_POLICY_CN' <c:if test="${searchCondition == 'INDVDL_INF_POLICY_CN'}">selected</c:if>><spring:message code="ussSamIpm.indvdlInfoPolicyList.indvdlInfoPolicyCn"/></option><!-- 개인정보보호정책내용 -->
				</select>
				<input class="s_input2 vat" type="text" name="searchKeyword" value="${searchVO.searchKeyword}" size="25" title="<spring:message code="title.search"/>" /><!-- 검색어 -->
				
				<input class="s_btn" type="submit" value="<spring:message code="button.inquire" />" title="<spring:message code="button.inquire" />" onclick="fn_egov_search_IndvdlInfoPolicy(); return false;" />
				<span class="btn_b"><a href="<c:url value='/uss/sam/ipm/registIndvdlInfoPolicy.do' />" onclick="fn_userChk('USRCNFRM_00000000000')"><spring:message code="button.create" /></a></span>
			</li>
		</ul>
	</div>
```

EgovIndvdlInfoPolicyRegist.jsp
아래 주석 부분 확인 부탁드립니다.
- `varFrom.onsubmit();`
```
 ******************************************************** */
function fn_egov_save_IndvdlInfoPolicy(){
	var varFrom = document.indvdlInfoPolicy;
	// varFrom.onsubmit();
	if(confirm("<spring:message code="common.save.msg" />")){
		varFrom.action =  "<c:url value='/uss/sam/ipm/registIndvdlInfoPolicy.do' />";
		if(!validateIndvdlInfoPolicy(varFrom)){
			return;
		}else{
			varFrom.submit();
		}
	}
}
```

**Comment by eGovFrameSupport** [comment]
표준프레임워크 발전을 위한 소중한 의견 감사 드립니다.
