### ISSUE TITLE
NoSQL 을 이용한 공통 컴포넌트들이 있으면 좋겠습니다

### ISSUE THREAD

**Issue by youngick** [eGovFramework/egovframe-common-components#26]
현재는 대부분 RDBMS를 이용하는 컴포넌트만 있는걸로 보이는데,
요즘은 RDBMS 이외에도 NoSQL (예를 들어 MongoDB, Redis, Cassandra, ...) 도 꽤 사용합니다.
용도에 맞도록 사용한다면 기존의 RDBMS 보다 더 좋은 서비스가 가능할거라 봅니다.
- 예를 들어 모니터링 데이터 같은 경우는 트랜잭션이나 테이블 간의 조인이 거의 필요 없으므로 
NoSQL 에 저장 하기에 적당해 보입니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
