### ISSUE TITLE
"HTTP서비스모니터링"에서 의심 가는 코드가 있습니다

### ISSUE THREAD

**Issue by youngick** [eGovFramework/egovframe-common-components#27]
https://www.egovframe.go.kr/wiki/doku.php?id=egovframework:com:v3.10:utl:sys:htm:http%EC%84%9C%EB%B9%84%EC%8A%A4%EB%AA%A8%EB%8B%88%ED%84%B0%EB%A7%81

코드를 수정하면 전체적으로 수정할 부분이 너무 많아져서 이슈로 남깁니다.

egovframework.com.utl.sys.htm.service 패키지에 보면
HttpMntrngScheduling 클래스의 monitorHttp 메소드에서 등록된 사이트들이 정상인지 
체크하는 부분이 있습니다. httpSttusCd = HttpMntrngChecker.getPrductStatus(siteUrl);

https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html

위 링크에서
sun.net.client.defaultConnectTimeout (default: -1)
sun.net.client.defaultReadTimeout (default: -1)
두 프로퍼티를 보면 기본값이 -1 로 되어 있는데 이것은 서버가 응답을 준비하는데 오래 걸릴 경우 경우, 
응답이 올때까지 계속 대기 상태에 빠질 위험이 있습니다. 
따라서 현재의 체크 방식 보다는 적절한 타임아웃 설정을 하고, 서버의 HTTP 응답 코드 또는 예외 발생 여부로 
판별하도록 전체 수정하는 것이 좋아 보입니다. 아래 링크를 참고하시면 좋습니다.

https://www.baeldung.com/httpclient-timeout

위의 문제는 실제로 타임아웃 설정이 없는 HTTP Client 코드로 연동 하는 사이트에서,
A->B->C 이런 식의 연쇄 장애로 이어져 결국 모든 시스템이 문제가 생기는 대형 장애로 되었던 사례입니다.

**Comment by eGovFrameSupport** [comment]
[2021 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'21년 3월 31일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2021 전자정부 표준프레임워크 컨트리뷰션"을 개최 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL 또는 첨부의 QR코드 인식하셔서 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

![2021컨트리뷰션 경품발송 설문](https://user-images.githubusercontent.com/3771788/127802383-83a27c34-d6a4-4772-8a3c-06399b12a169.png)

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
