### ISSUE TITLE
[기능요구(Feature)]: 동영상 업로드 및 보기 기능이 있으면 좋겠습니다

### ISSUE THREAD

**Issue by youngick** [eGovFramework/egovframe-common-components#298]
### 연락처 Contact

youngick@paran.com

### 추가 요청 기능명 Feature Name

동영상 업로드 및 보기 기능이 있으면 좋겠습니다

### 기능 상세 설명 Feature Description

요즘은 동영상 미디어를 많이 사용하는 추세인데 동영상 업로드 및 보기 기능이 없어보입니다.
예를 들어 '안전신문고' 라는 앱이 있는데 불법주차나 생활 속 안전 사고의 위험이 있는 것을 사진이나 영상으로 찍어서 올릴 수 있습니다. 
그런데 공통 컴포넌트에는 동영상 업로드 및 보기 기능이 없어보여서 의견 드립니다.
표준프레임워크 오픈 커뮤니티 게시판([https://open.egovframe.org/oc/support/bbs.do](https://open.egovframe.org/oc/support/bbs.do)) 에서도  
마찬가지로 동영상 업로드 및 보기를 할 수 없어 많이 불편합니다. 
힘드시겠지만 개선 되면 좋겠습니다. 감사합니다.

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크 발전을 위한 소중한 의견 감사 드립니다.
