### ISSUE TITLE
[Bug]: Maven > Update Project... 할때

### ISSUE THREAD

**Issue by KWANHYUNKIM** [eGovFramework/egovframe-common-components#349]
### 오류 내용 Error Description

![오류](https://github.com/eGovFramework/egovframe-common-components/assets/55569899/f5fa0f63-5825-4df6-a784-5a8d2f4ab727)

이렇게 오류가 발생하는데 이유가 있을까요? 

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 다음 메뉴를 선택한다. Select the following menu '...'
 2. 다음 버튼을 클릭한다. Click the Next button. '....'
 3. 다음 문구까지 스크롤 다운한다. Scroll down to the following phrase '....'
 4. 오류를 확인한다. Check for errors.

### 환경정보 Environmental Information

 - OS정보 Operating System: windows 11 
 - 표준프레임워크 버전 eGovFrame Version:  4.2 
 - JDK(JRE) 정보:  JDK 17
 - WAS 정보:  tomcat 9.0 
 - DB 정보:  
 - 기타 환경 정보 Other environmental information:

**Comment by eGovFrameSupport** [comment]
안녕하세요.
표준프레임워크 센터입니다.

해당 에러 메시지를 확인해 본 결과
Eclipse Memory 부족이 원인인 것으로 추정됩니다.
설치 경로로 가셔서
eclipse.ini를 텍스트 에디터로 여신 다음
-Xms256m (시작 힙 메모리)
-Xmx2048m (최대 힙 메모리)
에 해당되는 값을 보다 큰 값으로 할당해 보시기 바랍니다.

감사합니다.

**Comment by KWANHYUNKIM** [comment]
답변 감사합니다 :)
