### ISSUE TITLE
공통컴퍼넌트 테이블명 명명법 개선 문의

### ISSUE THREAD

**Issue by EricSeokgon** [eGovFramework/egovframe-common-components#59]
안녕 하세요~

공통컴퍼넌트를 사용할 때 처음에 가장 힘든점이 테이블명이 너무 약어로 되어 있어서 알아보기가 힘들었습니다.
이제는 어느정도 익숙해져서 괜찮은데 테이블 이름을 컬럼명 처럼 스네이크 표기법 혹은 좀더 사용자가 식별하기 쉽게 해주시면 좋겠습니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
