### ISSUE TITLE
전자정부프레임워크 위키 OAuth 내용 업데이트 개선

### ISSUE THREAD

**Issue by EricSeokgon** [eGovFramework/egovframe-common-components#61]
공통컴포넌트에서 제공하는 소스내용과 위키의 내용이 현행화가 안되어 있습니다.
https://www.egovframe.go.kr/wiki/doku.php?id=egovframework:oauth

1. Maven 설정
위키 내용

<dependency>
    <groupId>org.springframework.social</groupId>
    <artifactId>spring-social-facebook-web</artifactId>
    <version>1.1.1.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.springframework.social</groupId>
    <artifactId>spring-social-twitter</artifactId>
    <version>1.1.0.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.3.4</version>
    <exclusions>
        <exclusion>
            <artifactId>commons-logging</artifactId>
            <groupId>commons-logging</groupId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>1.4.180</version>
</dependency>

공통컴포넌트 내용

	    <dependency>
              <groupId>com.github.scribejava</groupId>
              <artifactId>scribejava-apis</artifactId>
              <version>5.6.0</version>
        </dependency>

        <dependency>
              <groupId>com.github.scribejava</groupId>
              <artifactId>scribejava-core</artifactId>
              <version>5.6.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.3.6</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-logging</artifactId>
                    <groupId>commons-logging</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.180</version>
        </dependency>

OAuth 로그인 버튼 구현(EgovLoginUsr.jsp)
위키 내용

  <[table](http://december.com/html/4/element/table.html) width="700">
    <[tr](http://december.com/html/4/element/tr.html)>
      <[td](http://december.com/html/4/element/td.html) class="title_left"><[img](http://december.com/html/4/element/img.html) src="<c:url value='/images/egovframework/com/cmm/icon/tit_icon.gif'/>" width="16" height="16" hspace="3" align="middle" alt="">&nbsp;OAuth 로그인</[td](http://december.com/html/4/element/td.html)>
    </[tr](http://december.com/html/4/element/tr.html)>
  </[table](http://december.com/html/4/element/table.html)>
    
    <[form](http://december.com/html/4/element/form.html) id="tw_signin" action="<c:url value="/signin/twitter"/>" method="POST" target="_blank">
        <[button](http://december.com/html/4/element/button.html) type="submit" style="width:151px; height:26px; background-image: url('<c:url value="/images/egovframework/com/ext/oauth/twitter/sign-in-with-twitter-d.png"/>');"/>
    </[form](http://december.com/html/4/element/form.html)>
    <[form](http://december.com/html/4/element/form.html) id="disconnect" action="/connect/twitter" method="post">
        <[button](http://december.com/html/4/element/button.html) type="submit">Disconnect from Twitter</[button](http://december.com/html/4/element/button.html)>  
        <[input](http://december.com/html/4/element/input.html) type="hidden" name="_method" value="delete" />
    </[form](http://december.com/html/4/element/form.html)>
    
    <[form](http://december.com/html/4/element/form.html) name="fb_signin" id="fb_signin" action="<c:url value="/signin/facebook"/>" method="POST" target="_blank">
        <[input](http://december.com/html/4/element/input.html) type="hidden" name="scope" value="publish_stream,email,offline_access" />
        <[button](http://december.com/html/4/element/button.html) type="submit" style="width:151px; height:26px; background-image: url('<c:url value="/images/egovframework/com/ext/oauth/facebook/sign-in-with-facebook.png"/>');"/>
    </[form](http://december.com/html/4/element/form.html)>
    <[form](http://december.com/html/4/element/form.html) id="disconnect" action="/connect/facebook" method="post">
        <[button](http://december.com/html/4/element/button.html) type="submit">Disconnect from Facebook</[button](http://december.com/html/4/element/button.html)> 
        <[input](http://december.com/html/4/element/input.html) type="hidden" name="_method" value="delete" />
    </[form](http://december.com/html/4/element/form.html)>

공통폼퍼넌트
<a href="${ naver_url }"><img width="300" src="<c:url value='/images/egovframework/com/uat/uia/naver-login.png'/>" alt="Naver Login" /></a>
	<br><br>
	<a href="${ google_url }"><img width="300" src="<c:url value='/images/egovframework/com/uat/uia/google-login.png'/>" alt="Google Login" /></a>
	<br><br>
	<a href="${ kakao_url }"><img width="300" src="<c:url value='/images/egovframework/com/uat/uia/kakao-login.png'/>" alt="Kakao Login" /></a>

* 전자정부 프레임워크 위키에는 OAuth 예전 버전으로 페이스북, 트위터에 대한 내용이고
* 공통컴포넌트 소스상의 내용은 OAuth2 버전으로 페이스북, 네이버, 카카오톡 내용으로 소스상과 위키의 설명이 다릅니다.
* 위키의 현행화가 되면 좋겠습니다.

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 개최 하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL 또는 첨부의 QR코드 인식하셔서 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
