### ISSUE TITLE
공통모듈 통계/리포팅 개선 진행 요청

### ISSUE THREAD

**Issue by teria9** [eGovFramework/egovframe-common-components#63]
전자정부표준프레임워크 공통컴포넌트에서 
통계/리포팅 부분에서 그래프로 표현시 막대그래프로만 적용하고 있습니다.
계속적으로 시스템사용자들의 요구사항이 다양해지고 요구사항이 많아 지고 있는 현황입니다.
하여. 시스템 개발시 별도의 차트 패키지를 구매하는 등 
개발자들이 차트 적용이 어려움을 많이 느끼고 있는 부분입니다.
저도 이런 부분을 고민하고 다양한 차트를 적용한 노하우가 있습니다.
제가 그동안 고민하고 적용 노하우를 바탕으로 프리웨어 차트라이브러리를 적용하여 개선하는 방향으로
컨티리뷰트하는 방향으로 개선을 진행하고자 하오니 검토 부탁드립니다.
전자정부표준프레임워크 개발자들에게 더 좋은 도구가 될 수 있도록 신속히 진행되었으면 합니다.
감사합니다.

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 개최 하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL 또는 첨부의 QR코드 인식하셔서 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
