### ISSUE TITLE
배포시 DB 설정에 관한 건

### ISSUE THREAD

**Issue by DavidEugen** [eGovFramework/egovframe-common-components#69]
현재 MySQL이 기본 DB 로 제공되고 있습니다.
그러다 보니 일단 개발 환경에 MySql 서버가 설치되어 있어야 하고, Connection 정보를 설정해 주어야 합니다.

표준프레임워크 교육을 이수한 사용자나, 경험이 있는 사용자들은 금방 DB 설정을 찾아가 문제를 해결할 것입니다.
그러나 처음 전자정부 프레임워크를 접하는 사용자들이 빠르게 데모를 실행 시키려다보니 DB 설정 부분을 놓쳐 또하나의 진입 장벽이 되는 것 같습니다.

처음 접하는 사용자도 한번에 바로 실행 할 수 있는 Hsql 환경으로 설정 해 주면 
전자정부 표준프레임워크를 처음 접하는 사용자들의 첫인상이나 인식 또한 개선되지 않을까 생각됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
