### ISSUE TITLE
코딩 컨벤션을 정의했으면 좋겠습니다.

### ISSUE THREAD

**Issue by DavidEugen** [eGovFramework/egovframe-common-components#70]
공통컴포넌트 같이 규모가 있는은 소스의 규모가 큰 만큼 소스별 다양한 개발 스타일들이 적용되어 있습니다.
이에 가독성도 떨어 질 뿐더러 유지보수 개발자들의 업무를 가중시키는 문제가 있는바
이에 코딩 컨벤션을 정의하고 통일된 규칙을 적용하므로써 효율성을 높이도록 하면 좋겠습니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
