### ISSUE TITLE
표준프레임워크 spring.profiles.active 사용에 대한 고려가 필요해 보입니다.

### ISSUE THREAD

**Issue by DavidEugen** [eGovFramework/egovframe-common-components#73]
현재 표준프레임워크의 초기화 과정에서 EgovWebServletContextListener.setEgovProfileSetting()이 사용되고 있습니다.

그런데 내부 로직을 뜻어보면 컨텍스트의  설정과정에서 시스템의 spring.profiles.active 를 식별 항목으로 사용하고 있는 듯 합니다.
```
System.setProperty("spring.profiles.active", EgovProperties.getProperty("Globals.DbType")+","+EgovProperties.getProperty("Globals.Auth"));
```

그러나 이는 Spring 자체에서 사용하는 profile 또한 이와 같은 key 값을 사용하고 있는바,
build 시에  spring.profiles.active 항목을 사용하고 있다면 예기치 못한 결과들이 발생 할 것 같습니다.
[참고](https://docs.spring.io/spring-boot/docs/1.2.0.M1/reference/html/boot-features-profiles.html)

표준프레임워크의 컨텍스트 식별을 위해서라면, 기존 표준프레임워크에서 내에서 사용하는 spring.profiles.active 프로퍼티를 확인 후 영향도를 확인하여 key의 명칭을 변경 해야 할 것 같습니다.

**Comment by rukegithub** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
