### ISSUE TITLE
공통으로 사용하는 변수들의 관리가 필요해 보입니다.

### ISSUE THREAD

**Issue by DavidEugen** [eGovFramework/egovframe-common-components#74]
현재 egovframework.com.cmm.service.Globals 에서 공통으로 사용하는 프로퍼티 변수, 혹은 글로벌 변수들을 관리하고 있는데
개별 소스에서는 개별 프로퍼티의 호출이 이루어 지고 있는것 같습니다.
```EgovProperties.getProperty()```
아무래도 꼭 필요한 경우가 아니라면 static final의 전역변수로 관리하는 비용이 EgovProperties.getProperty() 메소드 호출 비용보다 경제적으로 사용 할 수 있을 것같습니다.
꼭 필요한 경우가 아니라면, 공통 혹은 전역으로 사용되고 있는 변수값들은 한곳에서 관리하는것이 관리 비용이 줄어들 것으로 보입니다.

**Comment by rukegithub** [comment]
표준프레임워크에 대한 지속적인 참여에
대단히 감사드립니다.
